language: go

go:
  - 1.7

before_install:
  - echo "start before install no need di nothing"
install:
  - echo "start install no need go get"

before_script:
  - echo "start script before..."

script:
  - go run main.go &
  - sleep 5
  - go test -race -coverprofile=coverage.txt -covermode=atomic datastruct/*
  - go test -race -coverprofile=coverage.txt -covermode=atomic server/*

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1477125f-36b1-4df5-b6b0-f5267ff3f2d8

#
# before_deploy:
# deploy:
# after_deploy:
# after_script: