language: go

go:
  - 1.7

before_install:
  - go env
install:
  - echo "nothing"

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic datastruct/*

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1477125f-36b1-4df5-b6b0-f5267ff3f2d8